name: Build pdf
on:
  push
jobs:
  create_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile basic LaTeX document
        uses: ./
        with:
          root_file: example.tex
          working_directory: /
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: test
          path: test
        if: always()

# see https://github.com/xu-cheng/latex-action