name: Build pdf
on: push
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: example.tex
          latexmk_use_xelatex: true
          extra_fonts: |
            ./assets/fonts/Libertinus-7.040/static/OTF/*.otf
      - name: version
        run: echo "::set-output name=version::$(date +"%Y-%m-%dT%H:%M:%S%z")"
        id: version
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: example.pdf
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: example.pdf